import type { Metadata } from 'next';
import { Montserrat, Frauncesu } from 'next/font/google';
import './globals.css';

const montSerrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  variable: '--font-montSerrat',
});

const frauncesu = Frauncesu({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  variable: '--font-frauncesu',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montSerrat.variable} ${frauncesu.variable}`}>
        {children}
      </body>
    </html>
  );
}
